language: node_js
node_js:
- node
deploy:
  provider: npm
  skip_cleanup: true
  email: admin@cupsapp.com
  api_key:
    secure: bq9APF5dzzfCAA9RK5MoRp/mRO3FNGuij/5ZIpRcrGRZnBPET7Vrq75ID1LSusP3/DWEWd0YjmGzw+VP0bOCZKGCRKhkF2R45BQCNYP+IvwyM10if4lMR/1w4ZtmnyjHvi/OnbLfjM3TvmWbC3zMMIGfb5kNJU3YNxS1uFWtv0u/QwxZHIPCNFmKuH6DVYbkgDuCvqJMCi5ELkUsOeFZnLtNPnSbQKUZytXC7VKR9Hx1AAKxeU15ZAsFpOOt+8bhUyNdM3haYPSkygRCu20ovfku7aQs5d1R1FIajTxaK1X1ELg5PSIaFLMgwTIE6Hb5OaL3LrBLbXaFtQY23NZPRx/AeJLp00wKA4hU87EBc5TFP03O/LmXUo58BE/UW1arfYvhRGwu0PnhvQR65zQfJgt3Bu0SKr3AYBHsRJrsjyC1A4/zFeK3CuT5TK95Ai4lgvm/DsTWCLL+J4G4mB0a7Ea3iOZsUhZU2duznAunnLiTLfrEq4nvawLmacDU/AUtwQDpjsvSYM4Zo2qCV1KYdaIcnf3it7gSc2DehYPfhO98dNPzO3jEN+0wnVqH1im+80D/8b83uDj9vGbp5I729ZETiVjCflpTG0Kmql1sibC8+omXiU8ED5jN9d+rU7y5zj51NSbbicgy9JELkzTUuFBx4dTwxgipGcJkkImtkxQ=
  on:
    repo: urbancups/node-sheets
